name: Python package
on:
  release:
    types:
      - created
jobs:
  build-and-upload:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Install requirements
        run: python -m pip install requests
      - name: Build
        run: python -m build --sdist --wheel --outdir dist/
      - name: Test
        run: python -m unittest
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}